spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/demo?sslmode=disable
    username: postgres
    password: password
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
